#!/usr/bin/env python3
"""Local analyzer and generator for agent-contracts.

The script is intentionally deterministic and standard-library only. It reads
repository files, builds a module map, generates contract documents, reports
drift, and creates bounded context packs without executing target code.
"""

from __future__ import annotations

import argparse
import ast
import dataclasses
import datetime as dt
import fnmatch
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import textwrap
from pathlib import Path
from typing import Any

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover - Python < 3.11 fallback
    tomllib = None  # type: ignore[assignment]


PRODUCT = "agent-contracts"
GENERATED_BY = "<!-- Generated by agent-contracts. Review before editing. -->"
MAP_PATH = ".agent-contracts/module-map.json"
CONTEXT_PACK_ROOT = ".agent-contracts/context-packs"
NOW_FORMAT = "%Y-%m-%dT%H:%M:%SZ"

EXCLUDED_DIRS = {
    ".git",
    ".hg",
    ".svn",
    ".agent-contracts",
    ".pytest_cache",
    ".ruff_cache",
    ".mypy_cache",
    ".tox",
    ".venv",
    "venv",
    "env",
    "__pycache__",
    "node_modules",
    "bower_components",
    "dist",
    "build",
    "coverage",
    ".coverage",
    ".next",
    ".nuxt",
    ".turbo",
    ".cache",
    "target",
    "out",
    "vendor",
    "Pods",
    "DerivedData",
}

GENERATED_HINTS = {
    "generated",
    "gen",
    "__generated__",
    "snapshots",
    ".snapshots",
}

TEXT_EXTENSIONS = {
    ".c",
    ".cc",
    ".cfg",
    ".conf",
    ".cs",
    ".css",
    ".go",
    ".h",
    ".hpp",
    ".html",
    ".java",
    ".js",
    ".json",
    ".jsx",
    ".kt",
    ".lock",
    ".md",
    ".mjs",
    ".php",
    ".properties",
    ".py",
    ".rb",
    ".rs",
    ".scss",
    ".sh",
    ".sql",
    ".swift",
    ".toml",
    ".ts",
    ".tsx",
    ".txt",
    ".xml",
    ".yaml",
    ".yml",
}

LANG_BY_EXT = {
    ".py": "python",
    ".js": "javascript",
    ".jsx": "javascript",
    ".mjs": "javascript",
    ".ts": "typescript",
    ".tsx": "typescript",
    ".go": "go",
    ".rb": "ruby",
    ".java": "java",
    ".kt": "kotlin",
    ".swift": "swift",
    ".rs": "rust",
    ".cs": "csharp",
    ".php": "php",
}

MANIFEST_NAMES = {
    "package.json",
    "pyproject.toml",
    "setup.py",
    "setup.cfg",
    "requirements.txt",
    "poetry.lock",
    "Pipfile",
    "Cargo.toml",
    "go.mod",
    "pom.xml",
    "build.gradle",
    "Makefile",
}

CONFIG_NAMES = {
    ".env",
    ".env.example",
    ".eslintrc",
    ".prettierrc",
    "tsconfig.json",
    "vite.config.ts",
    "webpack.config.js",
    "next.config.js",
    "pytest.ini",
    "tox.ini",
    "ruff.toml",
    "mypy.ini",
    "Dockerfile",
    "docker-compose.yml",
}

TEST_RE = re.compile(r"(^|/)(tests?|specs?)(/|$)|(^|/).*([_.-](test|spec))\.(py|js|jsx|ts|tsx|rb|go|rs)$")
PY_ROUTE_RE = re.compile(r"@\s*(?:app|router|blueprint)\.(get|post|put|patch|delete|route)\(\s*['\"]([^'\"]+)['\"]")
JS_ROUTE_RE = re.compile(r"\b(?:app|router)\.(get|post|put|patch|delete|route)\(\s*['`\"]([^'`\"]+)['`\"]")
PY_PUBLIC_RE = re.compile(r"^(?:async\s+)?def\s+([A-Za-z][A-Za-z0-9_]*)\(|^class\s+([A-Za-z][A-Za-z0-9_]*)\(", re.M)
JS_EXPORT_RE = re.compile(
    r"\bexport\s+(?:async\s+)?(?:function|class|const|let|var|interface|type)\s+([A-Za-z][A-Za-z0-9_]*)"
)
MAKE_TARGET_RE = re.compile(r"^([A-Za-z0-9_.-]+):(?:\s|$)", re.M)
README_COMMAND_RE = re.compile(r"\b((?:npm|pnpm|yarn|python|python3|pytest|make|bun|cargo|go)\s+[^\n`]+)")


@dataclasses.dataclass
class FileInfo:
    path: str
    size: int
    language: str
    role: str


@dataclasses.dataclass
class ImportRef:
    source: str
    raw: str
    resolved_path: str | None = None
    target_module: str | None = None
    is_internal: bool = False


@dataclasses.dataclass
class ModuleInfo:
    name: str
    root: str
    kind: str
    owned_files: list[str]
    source_files: list[str]
    test_files: list[str]
    docs: list[str]
    configs: list[str]
    manifests: list[str]
    commands: list[str]
    public_surfaces: list[str]
    dependencies: list[str]
    imports: list[ImportRef]
    package_names: list[str]
    capabilities: list[str]
    confidence: float
    boundary_notes: list[str]

    def to_dict(self) -> dict[str, Any]:
        result = dataclasses.asdict(self)
        result["imports"] = [dataclasses.asdict(item) for item in self.imports]
        return result


@dataclasses.dataclass
class Finding:
    severity: str
    code: str
    title: str
    evidence: str
    affected_files: list[str]
    local_fix: str

    def to_dict(self) -> dict[str, Any]:
        return dataclasses.asdict(self)


def utc_now() -> str:
    return dt.datetime.now(dt.UTC).strftime(NOW_FORMAT)


def stable_slug(value: str) -> str:
    slug = re.sub(r"[^A-Za-z0-9]+", "-", value.strip().lower()).strip("-")
    return slug or "root"


def rel_path(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def is_text_file(path: Path) -> bool:
    if path.name in MANIFEST_NAMES or path.name in CONFIG_NAMES:
        return True
    return path.suffix in TEXT_EXTENSIONS


def is_generated_path(path: str) -> bool:
    parts = set(Path(path).parts)
    return bool(parts & GENERATED_HINTS)


def safe_read(path: Path, limit: int = 500_000) -> str:
    try:
        if path.stat().st_size > limit:
            return ""
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""


def load_json(path: Path) -> dict[str, Any]:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}


def classify_file(path: str, language: str) -> str:
    base = Path(path).name
    if base == "SPEC.md":
        return "contract"
    if base == "AGENTS.md":
        return "agent-instructions"
    if base == "ARCHITECTURE.md":
        return "architecture"
    if TEST_RE.search(path):
        return "test"
    if base in MANIFEST_NAMES:
        return "manifest"
    if base in CONFIG_NAMES or path.startswith(".github/"):
        return "config"
    if base.lower().startswith("readme") or Path(path).suffix == ".md":
        return "docs"
    if language:
        return "source"
    return "other"


def inventory(repo: Path) -> list[FileInfo]:
    files: list[FileInfo] = []
    for dirpath, dirnames, filenames in os.walk(repo):
        current = Path(dirpath)
        dirnames[:] = [
            dirname
            for dirname in sorted(dirnames)
            if dirname not in EXCLUDED_DIRS and not is_generated_path(rel_path(current / dirname, repo))
        ]
        for filename in sorted(filenames):
            absolute = current / filename
            try:
                if not absolute.is_file() or not is_text_file(absolute):
                    continue
                relative = rel_path(absolute, repo)
                if is_generated_path(relative):
                    continue
                size = absolute.stat().st_size
            except OSError:
                continue
            language = LANG_BY_EXT.get(absolute.suffix, "")
            role = classify_file(relative, language)
            files.append(FileInfo(relative, size, language, role))
    return files


def prefix_match(path: str, root: str) -> bool:
    if root == ".":
        return True
    return path == root or path.startswith(root.rstrip("/") + "/")


def infer_candidate_roots(files: list[FileInfo]) -> set[str]:
    candidates: set[str] = set()
    source_paths = [file.path for file in files if file.role in {"source", "test", "manifest"}]

    for file in files:
        if file.role == "manifest":
            parent = Path(file.path).parent.as_posix()
            if parent != ".":
                candidates.add(parent)

    grouped_prefixes = {"apps", "packages", "services", "libs", "modules"}
    for path in source_paths:
        parts = Path(path).parts
        if not parts:
            continue
        if parts[0] in grouped_prefixes and len(parts) >= 2:
            candidates.add(Path(parts[0], parts[1]).as_posix())
        elif parts[0] == "src" and len(parts) >= 3:
            candidates.add(Path(parts[0], parts[1]).as_posix())
        elif parts[0] == "src" and len(parts) == 2:
            candidates.add("src")
        elif len(parts) >= 2 and parts[0] not in {"test", "tests", "spec", "specs", "docs"}:
            candidates.add(parts[0])

    if not candidates:
        candidates.add(".")

    source_counts = {
        candidate: sum(1 for file in files if file.role in {"source", "test"} and prefix_match(file.path, candidate))
        for candidate in candidates
    }
    candidates = {candidate for candidate in candidates if source_counts.get(candidate, 0) > 0}

    if not candidates:
        candidates.add(".")

    return candidates


def module_name_from_root(root: str) -> str:
    if root == ".":
        return "root"
    parts = Path(root).parts
    if len(parts) >= 2 and parts[0] in {"apps", "packages", "services", "libs", "modules"}:
        return stable_slug(parts[-1])
    return stable_slug(parts[-1])


def deepest_candidate(path: str, candidates: set[str]) -> str | None:
    matches = [candidate for candidate in candidates if prefix_match(path, candidate)]
    if not matches:
        return None
    return max(matches, key=lambda item: len(Path(item).parts) if item != "." else 0)


def parse_package_json(repo: Path, path: str) -> tuple[str | None, list[str]]:
    data = load_json(repo / path)
    name = data.get("name") if isinstance(data.get("name"), str) else None
    scripts = data.get("scripts") if isinstance(data.get("scripts"), dict) else {}
    commands = [f"npm run {key}" for key in sorted(scripts)]
    return name, commands


def parse_pyproject(repo: Path, path: str) -> tuple[str | None, list[str]]:
    if tomllib is None:
        return None, []
    try:
        data = tomllib.loads((repo / path).read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError):
        return None, []
    project = data.get("project") if isinstance(data.get("project"), dict) else {}
    name = project.get("name") if isinstance(project.get("name"), str) else None
    scripts = project.get("scripts") if isinstance(project.get("scripts"), dict) else {}
    commands = [key for key in sorted(scripts)]
    tool = data.get("tool") if isinstance(data.get("tool"), dict) else {}
    poetry = tool.get("poetry") if isinstance(tool.get("poetry"), dict) else {}
    poetry_scripts = poetry.get("scripts") if isinstance(poetry.get("scripts"), dict) else {}
    commands.extend(key for key in sorted(poetry_scripts) if key not in commands)
    return name, commands


def extract_make_commands(repo: Path, path: str) -> list[str]:
    text = safe_read(repo / path)
    commands = []
    for match in MAKE_TARGET_RE.finditer(text):
        target = match.group(1)
        if not target.startswith("."):
            commands.append(f"make {target}")
    return sorted(set(commands))


def extract_readme_commands(repo: Path, path: str) -> list[str]:
    text = safe_read(repo / path)
    commands = []
    for match in README_COMMAND_RE.finditer(text):
        command = " ".join(match.group(1).strip().split())
        if len(command) <= 100:
            commands.append(command)
    return sorted(set(commands))[:8]


def extract_commands(repo: Path, files: list[str]) -> tuple[list[str], list[str]]:
    package_names: list[str] = []
    commands: list[str] = []
    for path in files:
        base = Path(path).name
        if base == "package.json":
            name, found = parse_package_json(repo, path)
            if name:
                package_names.append(name)
            commands.extend(found)
        elif base == "pyproject.toml":
            name, found = parse_pyproject(repo, path)
            if name:
                package_names.append(name)
            commands.extend(found)
        elif base == "Makefile":
            commands.extend(extract_make_commands(repo, path))
        elif base.lower().startswith("readme"):
            commands.extend(extract_readme_commands(repo, path))
    return sorted(set(package_names)), sorted(set(commands))


def extract_public_surfaces(repo: Path, file: FileInfo) -> list[str]:
    text = safe_read(repo / file.path)
    surfaces: list[str] = []
    if not text:
        return surfaces
    if file.language == "python":
        for method, route in PY_ROUTE_RE.findall(text):
            surfaces.append(f"route {method.upper()} {route}")
        for function_name, class_name in PY_PUBLIC_RE.findall(text):
            name = function_name or class_name
            if name and not name.startswith("_"):
                kind = "class" if class_name else "function"
                surfaces.append(f"{kind} {name}")
    elif file.language in {"javascript", "typescript"}:
        for method, route in JS_ROUTE_RE.findall(text):
            surfaces.append(f"route {method.upper()} {route}")
        for name in JS_EXPORT_RE.findall(text):
            if not name.startswith("_"):
                surfaces.append(f"export {name}")
        if "/app/" in f"/{file.path}" and Path(file.path).name in {"route.ts", "route.js"}:
            route_path = "/" + "/".join(Path(file.path).parts[1:-1])
            surfaces.append(f"route file {route_path}")
    return sorted(set(surfaces))


def py_imports(repo: Path, file: FileInfo) -> list[str]:
    text = safe_read(repo / file.path)
    if not text:
        return []
    try:
        tree = ast.parse(text)
    except SyntaxError:
        return []
    imports: list[str] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            imports.extend(alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom):
            prefix = "." * node.level
            module = node.module or ""
            imports.append(prefix + module)
    return imports


def js_imports(repo: Path, file: FileInfo) -> list[str]:
    text = safe_read(repo / file.path)
    if not text:
        return []
    patterns = [
        re.compile(r"\bimport\s+(?:[^'\"]+\s+from\s+)?['\"]([^'\"]+)['\"]"),
        re.compile(r"\bexport\s+[^'\"]+\s+from\s+['\"]([^'\"]+)['\"]"),
        re.compile(r"\brequire\(\s*['\"]([^'\"]+)['\"]\s*\)"),
    ]
    imports: list[str] = []
    for pattern in patterns:
        imports.extend(pattern.findall(text))
    return imports


def import_strings(repo: Path, file: FileInfo) -> list[str]:
    if file.language == "python":
        return py_imports(repo, file)
    if file.language in {"javascript", "typescript"}:
        return js_imports(repo, file)
    return []


def find_existing_path(repo: Path, candidate: Path) -> str | None:
    suffixes = ["", ".py", ".js", ".jsx", ".ts", ".tsx", "/__init__.py", "/index.js", "/index.ts", "/index.tsx"]
    for suffix in suffixes:
        path = (repo / (candidate.as_posix() + suffix)).resolve()
        if path.is_file():
            try:
                return rel_path(path, repo)
            except ValueError:
                return None
    return None


def resolve_import_path(repo: Path, source: str, raw: str, package_to_module: dict[str, ModuleInfo]) -> str | None:
    source_parent = Path(source).parent
    if raw.startswith("."):
        if raw.startswith("./") or raw.startswith("../"):
            return find_existing_path(repo, source_parent / raw)
        level = len(raw) - len(raw.lstrip("."))
        module_part = raw[level:]
        base = source_parent
        for _ in range(max(level - 1, 0)):
            base = base.parent
        if module_part:
            base = base / Path(*module_part.split("."))
        return find_existing_path(repo, base)

    if raw in package_to_module:
        module = package_to_module[raw]
        return module.source_files[0] if module.source_files else module.root

    top = raw.split(".")[0].split("/")[0]
    for module in package_to_module.values():
        root_leaf = Path(module.root).name if module.root != "." else module.name
        aliases = {module.name.replace("-", "_"), root_leaf.replace("-", "_")}
        if top.replace("-", "_") in aliases:
            return module.source_files[0] if module.source_files else module.root
    return None


def derive_capabilities(module_name: str, public_surfaces: list[str], source_files: list[str]) -> list[str]:
    capabilities = [f"{module_name}-module"]
    route_count = sum(1 for surface in public_surfaces if surface.startswith("route "))
    export_count = sum(1 for surface in public_surfaces if surface.startswith(("export ", "function ", "class ")))
    if route_count:
        capabilities.append("http-api")
    if export_count:
        capabilities.append("public-api")
    if any("command" in path or "cli" in path for path in source_files):
        capabilities.append("command-interface")
    return sorted(set(capabilities))


def module_kind(files: list[FileInfo], surfaces: list[str]) -> str:
    basenames = {Path(file.path).name for file in files}
    if "package.json" in basenames or "pyproject.toml" in basenames:
        return "package"
    if any(surface.startswith("route ") for surface in surfaces):
        return "service"
    if any(file.role == "source" for file in files):
        return "component"
    return "module"


def attach_external_tests(repo: Path, modules: list[ModuleInfo], unassigned: list[FileInfo]) -> None:
    for file in unassigned:
        if file.role != "test":
            continue
        text = safe_read(repo / file.path).lower()
        path_hint = stable_slug(file.path)
        scored_matches: list[tuple[int, ModuleInfo]] = []
        for module in modules:
            aliases = {module.name, module.name.replace("-", "_")}
            if module.root != ".":
                aliases.add(Path(module.root).name.replace("-", "_"))
            aliases.update(package.replace("-", "_") for package in module.package_names)
            score = 0
            if any(alias and alias.lower() in path_hint for alias in aliases):
                score += 3
            if any(alias and re.search(rf"['\"./@-]{re.escape(alias.lower())}[/.'\"]?", text) for alias in aliases):
                score += 1
            if module.root != "." and module.root.lower() in text:
                score += 2
            if score:
                scored_matches.append((score, module))
        if scored_matches:
            scored_matches.sort(key=lambda item: item[0], reverse=True)
            if len(scored_matches) > 1 and scored_matches[0][0] == scored_matches[1][0]:
                continue
            module = scored_matches[0][1]
            if file.path not in module.owned_files:
                module.owned_files.append(file.path)
                module.owned_files.sort()
            if file.path not in module.test_files:
                module.test_files.append(file.path)
                module.test_files.sort()
            note = f"Test file `{file.path}` is outside the module root and was associated by local evidence."
            if note not in module.boundary_notes:
                module.boundary_notes.append(note)


def build_module_map(repo: Path) -> dict[str, Any]:
    files = inventory(repo)
    candidates = infer_candidate_roots(files)
    assigned: dict[str, list[FileInfo]] = {candidate: [] for candidate in candidates}
    root_bucket: list[FileInfo] = []
    unassigned: list[FileInfo] = []

    for file in files:
        candidate = deepest_candidate(file.path, candidates)
        if candidate:
            assigned[candidate].append(file)
        elif file.role in {"manifest", "config", "docs", "architecture", "agent-instructions"}:
            root_bucket.append(file)
        else:
            unassigned.append(file)

    if root_bucket and "." not in assigned:
        assigned["."] = root_bucket
    elif root_bucket:
        assigned["."].extend(root_bucket)

    modules: list[ModuleInfo] = []
    used_names: dict[str, int] = {}
    for root in sorted(assigned, key=lambda item: (item == ".", item)):
        module_files = sorted(assigned[root], key=lambda file: file.path)
        if not module_files:
            continue
        base_name = module_name_from_root(root)
        used_names[base_name] = used_names.get(base_name, 0) + 1
        name = base_name if used_names[base_name] == 1 else f"{base_name}-{used_names[base_name]}"
        owned_files = [file.path for file in module_files]
        source_files = [file.path for file in module_files if file.role == "source"]
        test_files = [file.path for file in module_files if file.role == "test"]
        docs = [file.path for file in module_files if file.role in {"docs", "architecture"}]
        configs = [file.path for file in module_files if file.role == "config"]
        manifests = [file.path for file in module_files if file.role == "manifest"]
        package_names, commands = extract_commands(repo, owned_files)
        public_surfaces: list[str] = []
        for file in module_files:
            if file.role == "source":
                public_surfaces.extend(extract_public_surfaces(repo, file))
        public_surfaces = sorted(set(public_surfaces))
        confidence = 0.55
        if manifests:
            confidence += 0.2
        if source_files:
            confidence += 0.1
        if test_files:
            confidence += 0.1
        if docs:
            confidence += 0.05
        confidence = min(confidence, 0.98)
        notes: list[str] = []
        if not manifests:
            notes.append("No package manifest anchors this boundary.")
        if root == "." and len(candidates) > 1:
            notes.append("Root files support multiple modules and may contain shared repository instructions.")
        modules.append(
            ModuleInfo(
                name=name,
                root=root,
                kind=module_kind(module_files, public_surfaces),
                owned_files=owned_files,
                source_files=source_files,
                test_files=test_files,
                docs=docs,
                configs=configs,
                manifests=manifests,
                commands=commands,
                public_surfaces=public_surfaces,
                dependencies=[],
                imports=[],
                package_names=package_names,
                capabilities=derive_capabilities(name, public_surfaces, source_files),
                confidence=round(confidence, 2),
                boundary_notes=notes,
            )
        )

    attach_external_tests(repo, modules, unassigned)

    package_to_module: dict[str, ModuleInfo] = {}
    for module in modules:
        package_to_module[module.name] = module
        package_to_module[module.name.replace("-", "_")] = module
        if module.root != ".":
            package_to_module[Path(module.root).name.replace("-", "_")] = module
        for package_name in module.package_names:
            package_to_module[package_name] = module

    path_to_module: dict[str, ModuleInfo] = {}
    for module in modules:
        for path in module.owned_files:
            path_to_module[path] = module

    for module in modules:
        imports: list[ImportRef] = []
        dependencies: set[str] = set()
        source_infos = [file for file in files if file.path in set(module.source_files)]
        for file in source_infos:
            for raw in import_strings(repo, file):
                resolved = resolve_import_path(repo, file.path, raw, package_to_module)
                target_module = None
                is_internal = False
                if resolved:
                    target = deepest_candidate(resolved, {item.root for item in modules})
                    target_module = next((item.name for item in modules if item.root == target), None)
                    if target_module and target_module != module.name:
                        dependencies.add(target_module)
                        is_internal = "/internal/" in f"/{resolved}" or "/private/" in f"/{resolved}"
                imports.append(ImportRef(file.path, raw, resolved, target_module, is_internal))
        module.imports = sorted(imports, key=lambda item: (item.source, item.raw))
        module.dependencies = sorted(dependencies)

    return {
        "schema_version": 1,
        "product": PRODUCT,
        "generated_at": utc_now(),
        "repo_root": repo.as_posix(),
        "modules": [module.to_dict() for module in modules],
        "summary": {
            "file_count": len(files),
            "module_count": len(modules),
            "read_only": True,
        },
    }


def module_from_dict(data: dict[str, Any]) -> ModuleInfo:
    imports = [ImportRef(**item) for item in data.get("imports", [])]
    values = dict(data)
    values["imports"] = imports
    return ModuleInfo(**values)


def modules_from_map(map_data: dict[str, Any]) -> list[ModuleInfo]:
    return [module_from_dict(item) for item in map_data.get("modules", [])]


def yaml_list(items: list[str], indent: int = 2) -> str:
    if not items:
        return " []"
    prefix = " " * indent
    return "\n" + "\n".join(f"{prefix}- {item}" for item in items)


def generate_root_architecture(map_data: dict[str, Any]) -> str:
    modules = modules_from_map(map_data)
    lines = [
        GENERATED_BY,
        "",
        "# Repository Architecture",
        "",
        "This file records repository-wide module boundaries and invariants for AI coding agents.",
        "",
        "## Global Invariants",
        "- Treat module `SPEC.md` files as durable contracts.",
        "- Treat module `AGENTS.md` files as operating instructions for local work.",
        "- Do not import from another module's `internal/` or `private/` paths.",
        "- Prefer local verification commands recorded by the owning module.",
        "- Keep generated files concise and update them only after reviewing code evidence.",
        "",
        "## Module Contract Graph",
    ]
    for module in modules:
        deps = ", ".join(module.dependencies) if module.dependencies else "none"
        lines.append(f"- `{module.name}` (`{module.root}`): depends on {deps}; confidence {module.confidence:.2f}.")
    lines.extend(
        [
            "",
            "## Boundaries",
            "Module-owned files should be edited with the matching module contract in view. Shared root files apply to every module unless a module document is more specific.",
            "",
            f"Last reviewed: {utc_now()}",
            "",
        ]
    )
    return "\n".join(lines)


def generate_root_agents(map_data: dict[str, Any]) -> str:
    modules = modules_from_map(map_data)
    module_names = ", ".join(f"`{module.name}`" for module in modules) or "none detected"
    return "\n".join(
        [
            GENERATED_BY,
            "",
            "# Agent Instructions",
            "",
            "## Repository Scope",
            "Use `ARCHITECTURE.md` for global invariants and module `SPEC.md` files for local contracts.",
            "",
            "## Start Here",
            f"- Detected modules: {module_names}.",
            "- Run `python3 scripts/agent_contracts.py map --repo .` for a read-only module view.",
            "- Run `python3 scripts/agent_contracts.py check --repo .` before changing module contracts.",
            "",
            "## Editing Rules",
            "- Keep edits inside the target module unless the task explicitly crosses a declared dependency.",
            "- Do not overwrite generated contract files without user approval.",
            "- Do not execute untrusted repository code as part of contract analysis.",
            "- Record evidence for every contract or instruction change.",
            "",
            "## Verification",
            "Prefer module-specific commands recorded in module `AGENTS.md`. If none are present, inspect manifests and tests before running anything.",
            "",
        ]
    )


def generate_spec(module: ModuleInfo) -> str:
    deps = module.dependencies
    public_surfaces = module.public_surfaces or ["No public surface detected yet."]
    tests = module.test_files or ["No test evidence detected yet."]
    commands = module.commands or ["No local command detected yet."]
    return "\n".join(
        [
            "---",
            f"module: {module.name}",
            f"kind: {module.kind}",
            "status: active",
            "owners: []",
            f"owned_paths:{yaml_list([module.root + '/**' if module.root != '.' else '*'])}",
            f"depends_on:{yaml_list(deps)}",
            f"capabilities:{yaml_list(module.capabilities)}",
            f"last_reviewed: {utc_now()}",
            "---",
            "",
            f"# {module.name} SPEC",
            "",
            GENERATED_BY,
            "",
            "## Module Identity",
            f"`{module.name}` owns `{module.root}` and is classified as `{module.kind}`.",
            "",
            "## Owned Paths",
            *(f"- `{path}`" for path in module.owned_files[:40]),
            *([] if len(module.owned_files) <= 40 else [f"- ... {len(module.owned_files) - 40} more files"]),
            "",
            "## Public Contract",
            f"`{module.name}` provides the capabilities listed in this document. Changes to public surfaces, dependencies, or acceptance criteria require user review.",
            "",
            "## Capabilities Provided",
            *(f"- {capability}" for capability in module.capabilities),
            "",
            "## Dependencies",
            *([f"- `{dep}`" for dep in deps] if deps else ["- No module dependencies detected."]),
            "",
            "## Public Interfaces / Routes / Commands / Events",
            *(f"- {surface}" for surface in public_surfaces),
            *(f"- command: {command}" for command in commands),
            "",
            "## Acceptance Criteria",
            "- Public surfaces listed above remain stable unless this contract is updated with approval.",
            "- This module does not import another module's `internal/` or `private/` files.",
            "- Dependency changes are reflected in `depends_on`.",
            "- Important behavior has local test or review evidence.",
            "",
            "## Verification Evidence",
            *(f"- {item}" for item in tests),
            "",
            "## Internal Design Notes",
            "Internal-only implementation details should stay under local private paths where practical.",
            "",
            "## Known Constraints",
            *(f"- {note}" for note in module.boundary_notes[:6]),
            *([] if module.boundary_notes else ["- No constraints recorded yet."]),
            "",
            f"## Last Reviewed Timestamp",
            utc_now(),
            "",
        ]
    )


def generate_module_agents(module: ModuleInfo) -> str:
    commands = module.commands or ["No module command detected. Inspect manifests before running tests."]
    tests = module.test_files or ["No tests detected for this module."]
    deps = module.dependencies or ["No module dependencies detected."]
    return "\n".join(
        [
            GENERATED_BY,
            "",
            f"# {module.name} Agent Instructions",
            "",
            "## Module Scope",
            f"Work in `{module.root}` for changes owned by `{module.name}`.",
            "",
            "## Start Here",
            f"- Read `{module.root.rstrip('/') + '/' if module.root != '.' else ''}SPEC.md` before editing.",
            "- Inspect the source-to-test anchors below before changing behavior.",
            "",
            "## Owned Files",
            *(f"- `{path}`" for path in module.owned_files[:40]),
            *([] if len(module.owned_files) <= 40 else [f"- ... {len(module.owned_files) - 40} more files"]),
            "",
            "## Do Not Edit",
            "- Dependency internals from other modules.",
            "- Generated, vendor, build, cache, and dependency directories.",
            "- Public contract sections without user approval.",
            "",
            "## Local Commands",
            *(f"- {command}" for command in commands),
            "",
            "## Source-to-Test Anchors",
            *(f"- {item}" for item in tests),
            "",
            "## Dependency Rules",
            *(f"- {dep}" for dep in deps),
            "- Do not import another module's `internal/` or `private/` paths.",
            "",
            "## Common Failure Modes",
            "- Contract drift after moving files or adding public exports.",
            "- Missing test evidence for declared behavior.",
            "- Hidden cross-module imports that bypass a public surface.",
            "",
        ]
    )


def file_plan_for_init(repo: Path, map_data: dict[str, Any]) -> list[tuple[Path, str, str]]:
    modules = modules_from_map(map_data)
    planned = [
        (repo / "ARCHITECTURE.md", "root architecture invariants", generate_root_architecture(map_data)),
        (repo / "AGENTS.md", "root agent instructions", generate_root_agents(map_data)),
        (repo / MAP_PATH, "module map JSON", json.dumps(map_data, indent=2) + "\n"),
    ]
    for module in modules:
        base = repo if module.root == "." else repo / module.root
        planned.append((base / "SPEC.md", f"{module.name} module contract", generate_spec(module)))
        if module.root != ".":
            planned.append((base / "AGENTS.md", f"{module.name} agent instructions", generate_module_agents(module)))
    return planned


def prompt_yes_no(question: str) -> bool:
    try:
        answer = input(f"{question} [y/N] ").strip().lower()
    except EOFError:
        return False
    return answer in {"y", "yes"}


def write_planned_files(
    planned: list[tuple[Path, str, str]],
    *,
    yes: bool,
    overwrite_existing: bool,
) -> dict[str, list[str]]:
    existing = [path for path, _, _ in planned if path.exists()]
    if not yes and not prompt_yes_no(f"Write {len(planned)} generated files?"):
        return {"written": [], "skipped_existing": [], "skipped_other": [path.as_posix() for path, _, _ in planned]}
    if existing and not yes and not prompt_yes_no(f"Overwrite {len(existing)} existing files?"):
        return {
            "written": [],
            "skipped_existing": [path.as_posix() for path in existing],
            "skipped_other": [],
        }
    result = {"written": [], "skipped_existing": [], "skipped_other": []}
    for path, _, contents in planned:
        if path.exists() and not overwrite_existing:
            result["skipped_existing"].append(path.as_posix())
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(contents, encoding="utf-8")
        result["written"].append(path.as_posix())
    return result


def find_git_root(repo: Path) -> Path | None:
    current = repo.resolve()
    for candidate in [current, *current.parents]:
        if (candidate / ".git").exists():
            return candidate
    return None


def plugin_required_paths() -> list[str]:
    return [
        ".claude-plugin/plugin.json",
        "commands/contract-init.md",
        "commands/contract-map.md",
        "commands/contract-check.md",
        "commands/contract-refresh.md",
        "commands/context-pack.md",
        "commands/contract-doctor.md",
        "skills/contract-init/SKILL.md",
        "skills/contract-map/SKILL.md",
        "skills/contract-check/SKILL.md",
        "skills/contract-refresh/SKILL.md",
        "skills/context-pack/SKILL.md",
        "skills/contract-doctor/SKILL.md",
        "skills/shared/safety.md",
        "skills/shared/analyzer-contract.md",
        "skills/shared/generated-files.md",
        "skills/shared/script-resolution.md",
        "scripts/agent_contracts.py",
    ]


def add_doctor_check(checks: list[dict[str, str]], name: str, status: str, detail: str) -> None:
    checks.append({"name": name, "status": status, "detail": detail})


def run_git(repo: Path, *args: str) -> subprocess.CompletedProcess[str] | None:
    if shutil.which("git") is None:
        return None
    return subprocess.run(
        ["git", *args],
        cwd=repo,
        text=True,
        capture_output=True,
        check=False,
    )


def doctor_report(repo: Path) -> dict[str, Any]:
    checks: list[dict[str, str]] = []
    resolved_repo = repo.resolve()
    plugin_root = Path(__file__).resolve().parents[1]

    if resolved_repo.exists() and resolved_repo.is_dir():
        add_doctor_check(checks, "repository path", "ok", f"`{resolved_repo}` exists and is a directory.")
    else:
        add_doctor_check(checks, "repository path", "blocker", f"`{resolved_repo}` is not a readable directory.")
        return {"product": PRODUCT, "repo_root": resolved_repo.as_posix(), "checks": checks, "exit_code": 2}

    python_version = f"{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}"
    if sys.version_info >= (3, 10):
        add_doctor_check(checks, "python version", "ok", f"Python {python_version} is supported.")
    else:
        add_doctor_check(checks, "python version", "blocker", f"Python {python_version} is too old; Python 3.10+ is required.")

    missing_plugin_files = [relative for relative in plugin_required_paths() if not (plugin_root / relative).exists()]
    if missing_plugin_files:
        add_doctor_check(
            checks,
            "plugin layout",
            "blocker",
            "Missing plugin files: " + ", ".join(missing_plugin_files[:8]) + (" ..." if len(missing_plugin_files) > 8 else ""),
        )
    else:
        add_doctor_check(checks, "plugin layout", "ok", f"Required plugin files exist under `{plugin_root}`.")

    git_root = find_git_root(resolved_repo)
    if shutil.which("git") is None:
        add_doctor_check(checks, "git availability", "warning", "Git was not found on PATH; analysis still works, but repo status checks are limited.")
    elif git_root is None:
        add_doctor_check(checks, "git repository", "warning", "No `.git` directory found at or above the target path.")
    else:
        add_doctor_check(checks, "git repository", "ok", f"Git repository root detected at `{git_root}`.")
        status = run_git(resolved_repo, "status", "--short")
        if status is None:
            add_doctor_check(checks, "git status", "warning", "Git status could not be checked.")
        elif status.returncode == 0:
            count = len([line for line in status.stdout.splitlines() if line.strip()])
            detail = "Working tree is clean." if count == 0 else f"Working tree has {count} changed or untracked path(s)."
            add_doctor_check(checks, "git status", "ok", detail)
        else:
            add_doctor_check(checks, "git status", "warning", status.stderr.strip() or "Git status failed.")

    if os.access(resolved_repo, os.R_OK):
        add_doctor_check(checks, "read permission", "ok", "Repository path is readable.")
    else:
        add_doctor_check(checks, "read permission", "blocker", "Repository path is not readable.")

    if os.access(resolved_repo, os.W_OK):
        add_doctor_check(checks, "write permission", "ok", "Repository path is writable for approved generated files.")
    else:
        add_doctor_check(checks, "write permission", "warning", "Repository path is not writable; read-only commands can still run.")

    gitignore_path = resolved_repo / ".gitignore"
    if gitignore_path.exists():
        gitignore_text = safe_read(gitignore_path)
        expected_ignores = [".agent-contracts/cache/", ".agent-contracts/context-packs/"]
        missing_ignores = [item for item in expected_ignores if item not in gitignore_text]
        if missing_ignores:
            add_doctor_check(checks, "ignore rules", "warning", "Consider ignoring transient outputs: " + ", ".join(missing_ignores))
        else:
            add_doctor_check(checks, "ignore rules", "ok", "Transient agent-contracts outputs are ignored.")
    else:
        add_doctor_check(checks, "ignore rules", "warning", "No `.gitignore` found; generated caches and context packs may be accidentally committed.")

    sample = inventory(resolved_repo)
    if sample:
        add_doctor_check(checks, "inventory sample", "ok", f"Read-only inventory found {len(sample)} text file(s).")
    else:
        add_doctor_check(checks, "inventory sample", "warning", "No supported text files were found in the target repository.")

    blockers = sum(1 for check in checks if check["status"] == "blocker")
    warnings = sum(1 for check in checks if check["status"] == "warning")
    exit_code = 2 if blockers else 1 if warnings else 0
    return {
        "product": PRODUCT,
        "repo_root": resolved_repo.as_posix(),
        "plugin_root": plugin_root.as_posix(),
        "local_only": True,
        "checks": checks,
        "summary": {"blockers": blockers, "warnings": warnings, "ok": sum(1 for check in checks if check["status"] == "ok")},
        "exit_code": exit_code,
    }


def render_doctor_text(report: dict[str, Any]) -> str:
    status_by_exit = {0: "usable", 1: "usable with warnings", 2: "blocked"}
    lines = [
        f"{PRODUCT} doctor",
        f"Repository: {report.get('repo_root')}",
        f"Plugin: {report.get('plugin_root', 'unknown')}",
        f"Status: {status_by_exit.get(report.get('exit_code'), 'unknown')}",
        "Local-only: yes",
        "",
    ]
    for check in report.get("checks", []):
        lines.append(f"- [{check['status'].upper()}] {check['name']}: {check['detail']}")
    lines.extend(
        [
            "",
            "Next steps:",
        ]
    )
    if report.get("exit_code") == 2:
        lines.append("- Fix blocker checks before running write workflows.")
    elif report.get("summary", {}).get("warnings", 0):
        lines.append("- Review warnings, then run `contract-map` or `contract-init` when ready.")
    else:
        lines.append("- Run `contract-map` for a read-only module scan or `contract-init` to preview generated files.")
    return "\n".join(lines) + "\n"


def parse_frontmatter(text: str) -> dict[str, Any]:
    if not text.startswith("---\n"):
        return {}
    end = text.find("\n---", 4)
    if end == -1:
        return {}
    lines = text[4:end].splitlines()
    data: dict[str, Any] = {}
    current_key: str | None = None
    for line in lines:
        if not line.strip():
            continue
        if not line.startswith(" ") and ":" in line:
            key, value = line.split(":", 1)
            key = key.strip()
            value = value.strip()
            if value == "[]":
                data[key] = []
                current_key = key
            elif value:
                data[key] = value.strip("'\"")
                current_key = None
            else:
                data[key] = []
                current_key = key
        elif current_key and line.strip().startswith("- "):
            data.setdefault(current_key, []).append(line.strip()[2:].strip("'\""))
    return data


def specs_in_repo(repo: Path) -> dict[str, dict[str, Any]]:
    specs: dict[str, dict[str, Any]] = {}
    for path in repo.rglob("SPEC.md"):
        if any(part in EXCLUDED_DIRS for part in path.relative_to(repo).parts):
            continue
        text = safe_read(path)
        frontmatter = parse_frontmatter(text)
        module_name = str(frontmatter.get("module") or stable_slug(path.parent.name if path.parent != repo else "root"))
        specs[module_name] = {
            "path": rel_path(path, repo),
            "root": "." if path.parent == repo else rel_path(path.parent, repo),
            "frontmatter": frontmatter,
            "text": text,
        }
    return specs


def path_matches_declared(path: str, patterns: list[str]) -> bool:
    for pattern in patterns:
        normalized = pattern.strip()
        if normalized == "*":
            return "/" not in path
        if fnmatch.fnmatch(path, normalized):
            return True
        if normalized.endswith("/**") and prefix_match(path, normalized[:-3]):
            return True
    return False


def check_drift(repo: Path) -> list[Finding]:
    map_data = build_module_map(repo)
    modules = modules_from_map(map_data)
    specs = specs_in_repo(repo)
    findings: list[Finding] = []

    declared_paths: list[str] = []
    for spec in specs.values():
        owned = spec["frontmatter"].get("owned_paths", [])
        if isinstance(owned, list):
            declared_paths.extend(owned)

    if declared_paths:
        for file in inventory(repo):
            if file.role in {"contract", "agent-instructions", "architecture"}:
                continue
            if not path_matches_declared(file.path, declared_paths):
                findings.append(
                    Finding(
                        "medium",
                        "orphan-file",
                        "File is not covered by any declared module path",
                        f"`{file.path}` does not match any SPEC.md owned_paths entry.",
                        [file.path],
                        "Assign the file to a module SPEC.md or move it under an owned path.",
                    )
                )

    for module in modules:
        spec = specs.get(module.name)
        if not spec:
            findings.append(
                Finding(
                    "medium",
                    "missing-spec",
                    "Detected module has no SPEC.md",
                    f"`{module.name}` was detected at `{module.root}` but no matching SPEC.md was found.",
                    module.owned_files[:8],
                    "Run contract init or add a reviewed SPEC.md for this module.",
                )
            )
            continue

        frontmatter = spec["frontmatter"]
        declared_deps = set(frontmatter.get("depends_on", []) if isinstance(frontmatter.get("depends_on"), list) else [])
        actual_deps = set(module.dependencies)
        for dep in sorted(actual_deps - declared_deps):
            findings.append(
                Finding(
                    "high",
                    "undeclared-dependency",
                    "Code imports another module that is not declared",
                    f"`{module.name}` imports `{dep}` but `{dep}` is absent from depends_on.",
                    [item.source for item in module.imports if item.target_module == dep][:8],
                    f"Add `{dep}` to `{spec['path']}` depends_on or remove the cross-module import.",
                )
            )
        for dep in sorted(declared_deps):
            if dep not in specs:
                findings.append(
                    Finding(
                        "medium",
                        "missing-dependency-contract",
                        "Declared dependency has no contract",
                        f"`{module.name}` declares `{dep}`, but no `{dep}` SPEC.md was found.",
                        [spec["path"]],
                        f"Create a SPEC.md for `{dep}` or remove the stale dependency.",
                    )
                )

        for item in module.imports:
            if item.target_module and item.target_module != module.name and item.is_internal:
                findings.append(
                    Finding(
                        "high",
                        "internal-import",
                        "Module imports another module's internal file",
                        f"`{item.source}` imports `{item.raw}`, resolved to `{item.resolved_path}`.",
                        [item.source, item.resolved_path or ""],
                        "Replace the import with a public surface from the dependency module.",
                    )
                )

        spec_text = spec["text"].lower()
        for surface in module.public_surfaces:
            if surface.lower() not in spec_text:
                findings.append(
                    Finding(
                        "medium",
                        "undeclared-public-surface",
                        "Detected public surface is not listed in SPEC.md",
                        f"`{surface}` was detected for `{module.name}` but is absent from `{spec['path']}`.",
                        module.source_files[:8],
                        "Review the surface and add it to the SPEC.md or make it internal.",
                    )
                )

        declared_capabilities = frontmatter.get("capabilities", [])
        if isinstance(declared_capabilities, list) and declared_capabilities and not module.test_files:
            findings.append(
                Finding(
                    "low",
                    "missing-test-evidence",
                    "Declared capabilities have no detected test evidence",
                    f"`{module.name}` declares capabilities but no test files were detected under the module.",
                    [spec["path"]],
                    "Add local tests or record manual verification evidence in the SPEC.md.",
                )
            )

        agents_path = Path(spec["path"]).with_name("AGENTS.md")
        if module.root == ".":
            agents_path = Path("AGENTS.md")
        if not (repo / agents_path).exists():
            findings.append(
                Finding(
                    "medium",
                    "missing-agents",
                    "Module has no AGENTS.md instructions",
                    f"`{agents_path.as_posix()}` was not found for `{module.name}`.",
                    [spec["path"]],
                    "Generate or add module agent instructions with scope, commands, tests, and dependency rules.",
                )
            )
        else:
            agents_text = safe_read(repo / agents_path)
            required = ["Module Scope", "Start Here", "Dependency Rules"]
            missing = [section for section in required if section not in agents_text]
            if missing:
                findings.append(
                    Finding(
                        "low",
                        "stale-agents",
                        "AGENTS.md is missing expected instruction sections",
                        f"`{agents_path.as_posix()}` is missing: {', '.join(missing)}.",
                        [agents_path.as_posix()],
                        "Refresh AGENTS.md safe instruction sections from current code evidence.",
                    )
                )
    return findings


def render_map_text(map_data: dict[str, Any]) -> str:
    modules = modules_from_map(map_data)
    lines = [
        f"{PRODUCT} module map",
        f"Repository: {map_data.get('repo_root')}",
        f"Files inspected: {map_data.get('summary', {}).get('file_count', 0)}",
        "",
    ]
    for module in modules:
        lines.extend(
            [
                f"## {module.name}",
                f"- root: {module.root}",
                f"- kind: {module.kind}",
                f"- confidence: {module.confidence:.2f}",
                f"- owned files: {len(module.owned_files)}",
                f"- public surfaces: {', '.join(module.public_surfaces) if module.public_surfaces else 'none detected'}",
                f"- dependencies: {', '.join(module.dependencies) if module.dependencies else 'none detected'}",
                f"- tests: {', '.join(module.test_files) if module.test_files else 'none detected'}",
                f"- commands: {', '.join(module.commands) if module.commands else 'none detected'}",
            ]
        )
        if module.boundary_notes:
            lines.append(f"- boundary notes: {'; '.join(module.boundary_notes)}")
        lines.append("")
    return "\n".join(lines)


def render_findings_text(findings: list[Finding]) -> str:
    if not findings:
        return "No drift findings detected.\n"
    lines = [f"{PRODUCT} drift report", ""]
    order = {"high": 0, "medium": 1, "low": 2}
    for index, finding in enumerate(sorted(findings, key=lambda item: (order.get(item.severity, 9), item.code)), 1):
        lines.extend(
            [
                f"## {index}. [{finding.severity.upper()}] {finding.title}",
                f"- code: {finding.code}",
                f"- evidence: {finding.evidence}",
                f"- affected files: {', '.join(path for path in finding.affected_files if path) or 'none'}",
                f"- local fix: {finding.local_fix}",
                "",
            ]
        )
    return "\n".join(lines)


def cmd_map(args: argparse.Namespace) -> int:
    repo = Path(args.repo).resolve()
    map_data = build_module_map(repo)
    if args.format == "json":
        print(json.dumps(map_data, indent=2))
    else:
        print(render_map_text(map_data))
    return 0


def cmd_init(args: argparse.Namespace) -> int:
    repo = Path(args.repo).resolve()
    map_data = build_module_map(repo)
    planned = file_plan_for_init(repo, map_data)
    print(render_map_text(map_data))
    print("Planned generated files:")
    for path, description, _ in planned:
        state = "exists" if path.exists() else "new"
        print(f"- {path.relative_to(repo).as_posix()} ({description}, {state})")
    if not args.write:
        print("\nNo files written. Re-run with --write after user approval.")
        return 0
    result = write_planned_files(planned, yes=args.yes, overwrite_existing=args.overwrite_existing)
    print(json.dumps(result, indent=2))
    return 0


def cmd_check(args: argparse.Namespace) -> int:
    repo = Path(args.repo).resolve()
    findings = check_drift(repo)
    if args.format == "json":
        print(json.dumps({"findings": [finding.to_dict() for finding in findings]}, indent=2))
    else:
        print(render_findings_text(findings))
    if args.fail_on and any(finding.severity == args.fail_on for finding in findings):
        return 1
    return 0


def desired_refreshes(repo: Path) -> tuple[list[tuple[Path, str, str]], list[tuple[Path, str, str]]]:
    map_data = build_module_map(repo)
    modules = modules_from_map(map_data)
    safe: list[tuple[Path, str, str]] = [(repo / MAP_PATH, "module map JSON", json.dumps(map_data, indent=2) + "\n")]
    contract: list[tuple[Path, str, str]] = []
    for module in modules:
        base = repo if module.root == "." else repo / module.root
        agents_path = base / "AGENTS.md"
        spec_path = base / "SPEC.md"
        desired_agents = generate_module_agents(module) if module.root != "." else generate_root_agents(map_data)
        desired_spec = generate_spec(module)
        if not agents_path.exists() or safe_read(agents_path) != desired_agents:
            safe.append((agents_path, f"{module.name} safe instruction refresh", desired_agents))
        if not spec_path.exists() or safe_read(spec_path) != desired_spec:
            contract.append((spec_path, f"{module.name} contract-changing refresh", desired_spec))
    return safe, contract


def cmd_refresh(args: argparse.Namespace) -> int:
    repo = Path(args.repo).resolve()
    safe, contract = desired_refreshes(repo)
    print("Safe instruction refreshes:")
    for path, description, _ in safe:
        print(f"- {path.relative_to(repo).as_posix()} ({description})")
    print("\nContract-changing updates requiring approval:")
    for path, description, _ in contract:
        print(f"- {path.relative_to(repo).as_posix()} ({description})")
    if args.write_safe:
        result = write_planned_files(safe, yes=args.yes, overwrite_existing=True)
        print("\nSafe writes:")
        print(json.dumps(result, indent=2))
    if args.write_contract:
        result = write_planned_files(contract, yes=args.yes, overwrite_existing=True)
        print("\nContract writes:")
        print(json.dumps(result, indent=2))
    if not args.write_safe and not args.write_contract:
        print("\nNo files written.")
    return 0


def choose_module(modules: list[ModuleInfo], target: str) -> ModuleInfo | None:
    wanted = stable_slug(target)
    for module in modules:
        if module.name == wanted or module.root == target or wanted in {stable_slug(module.root), stable_slug(Path(module.root).name)}:
            return module
    for module in modules:
        haystack = " ".join([module.name, module.root, *module.public_surfaces, *module.capabilities]).lower()
        if target.lower() in haystack:
            return module
    return modules[0] if modules else None


def copy_pack_file(repo: Path, output_root: Path, rel: str, max_bytes: int) -> tuple[bool, str]:
    source = repo / rel
    if not source.exists() or not source.is_file():
        return False, "missing"
    try:
        if source.stat().st_size > max_bytes:
            return False, "too large"
    except OSError:
        return False, "unreadable"
    destination = output_root / "files" / rel
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, destination)
    return True, "included"


def build_context_pack(repo: Path, target: str, output: Path | None, max_files: int, max_bytes: int) -> Path:
    map_data = build_module_map(repo)
    modules = modules_from_map(map_data)
    module = choose_module(modules, target)
    if module is None:
        raise SystemExit("No modules detected.")
    digest = hashlib.sha1(f"{module.name}:{utc_now()}".encode("utf-8")).hexdigest()[:8]
    output_root = output or repo / CONTEXT_PACK_ROOT / f"{module.name}-{digest}"
    output_root.mkdir(parents=True, exist_ok=True)

    include_paths: list[str] = []
    for root_file in ["ARCHITECTURE.md", "AGENTS.md"]:
        if (repo / root_file).exists():
            include_paths.append(root_file)
    for contract_file in ["SPEC.md", "AGENTS.md"]:
        path = contract_file if module.root == "." else f"{module.root}/{contract_file}"
        if (repo / path).exists():
            include_paths.append(path)
    for dep_name in module.dependencies:
        dep = next((item for item in modules if item.name == dep_name), None)
        if dep:
            dep_spec = "SPEC.md" if dep.root == "." else f"{dep.root}/SPEC.md"
            if (repo / dep_spec).exists():
                include_paths.append(dep_spec)
    include_paths.extend(module.source_files)
    include_paths.extend(module.test_files)
    include_paths = list(dict.fromkeys(include_paths))

    included: list[str] = []
    omitted: list[dict[str, str]] = []
    total = 0
    for path in include_paths:
        if len(included) >= max_files:
            omitted.append({"path": path, "reason": "file limit"})
            continue
        size = (repo / path).stat().st_size if (repo / path).exists() else 0
        if total + size > max_bytes:
            omitted.append({"path": path, "reason": "byte limit"})
            continue
        ok, reason = copy_pack_file(repo, output_root, path, max_bytes)
        if ok:
            included.append(path)
            total += size
        else:
            omitted.append({"path": path, "reason": reason})

    manifest = {
        "product": PRODUCT,
        "created_at": utc_now(),
        "target": target,
        "module": module.to_dict(),
        "included_files": included,
        "omitted_files": omitted,
        "limits": {"max_files": max_files, "max_bytes": max_bytes},
    }
    (output_root / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    readme = [
        f"# Context Pack: {module.name}",
        "",
        GENERATED_BY,
        "",
        f"Target: `{target}`",
        f"Module root: `{module.root}`",
        "",
        "## Verification Commands",
        *([f"- {command}" for command in module.commands] if module.commands else ["- No command detected. Inspect manifests before running anything."]),
        "",
        "## Included Files",
        *(f"- `{path}`" for path in included),
        "",
        "## Omitted Files",
        *([f"- `{item['path']}`: {item['reason']}" for item in omitted] if omitted else ["- None"]),
        "",
    ]
    (output_root / "README.md").write_text("\n".join(readme), encoding="utf-8")
    return output_root


def cmd_context_pack(args: argparse.Namespace) -> int:
    repo = Path(args.repo).resolve()
    output = Path(args.output).resolve() if args.output else None
    pack = build_context_pack(repo, args.target, output, args.max_files, args.max_bytes)
    print(f"Context pack written to {pack}")
    return 0


def cmd_doctor(args: argparse.Namespace) -> int:
    repo = Path(args.repo).resolve()
    report = doctor_report(repo)
    if args.format == "json":
        print(json.dumps(report, indent=2))
    else:
        print(render_doctor_text(report))
    return int(report["exit_code"])


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="agent_contracts.py", description="Local module contract analyzer")
    subparsers = parser.add_subparsers(dest="command", required=True)

    doctor_parser = subparsers.add_parser("doctor", help="Check local plugin and repository readiness")
    doctor_parser.add_argument("--repo", default=".", help="Repository to inspect")
    doctor_parser.add_argument("--format", choices=["text", "json"], default="text")
    doctor_parser.set_defaults(func=cmd_doctor)

    map_parser = subparsers.add_parser("map", help="Read-only module map")
    map_parser.add_argument("--repo", default=".", help="Repository to inspect")
    map_parser.add_argument("--format", choices=["text", "json"], default="text")
    map_parser.set_defaults(func=cmd_map)

    init_parser = subparsers.add_parser("init", help="Propose or write initial contract files")
    init_parser.add_argument("--repo", default=".", help="Repository to inspect")
    init_parser.add_argument("--write", action="store_true", help="Write generated files after approval")
    init_parser.add_argument("--yes", action="store_true", help="Approve writes for non-existing files")
    init_parser.add_argument("--overwrite-existing", action="store_true", help="Allow overwriting existing generated paths")
    init_parser.set_defaults(func=cmd_init)

    check_parser = subparsers.add_parser("check", help="Read-only drift check")
    check_parser.add_argument("--repo", default=".", help="Repository to inspect")
    check_parser.add_argument("--format", choices=["text", "json"], default="text")
    check_parser.add_argument("--fail-on", choices=["high", "medium", "low"], help="Exit 1 when a finding has this severity")
    check_parser.set_defaults(func=cmd_check)

    refresh_parser = subparsers.add_parser("refresh", help="Plan safe and contract-changing updates")
    refresh_parser.add_argument("--repo", default=".", help="Repository to inspect")
    refresh_parser.add_argument("--write-safe", action="store_true", help="Write safe instruction refreshes")
    refresh_parser.add_argument("--write-contract", action="store_true", help="Write contract-changing updates after approval")
    refresh_parser.add_argument("--yes", action="store_true", help="Approve requested writes")
    refresh_parser.set_defaults(func=cmd_refresh)

    pack_parser = subparsers.add_parser("context-pack", help="Build a local context pack")
    pack_parser.add_argument("target", help="Module name, path, or task description")
    pack_parser.add_argument("--repo", default=".", help="Repository to inspect")
    pack_parser.add_argument("--output", help="Output directory")
    pack_parser.add_argument("--max-files", type=int, default=80)
    pack_parser.add_argument("--max-bytes", type=int, default=700_000)
    pack_parser.set_defaults(func=cmd_context_pack)

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
